parameters:
    webit_sencha.installer.class: Webit\Bundle\SenchaBundle\Component\Common\Installer
    webit_sencha.extjs_controller.class: Webit\Bundle\SenchaBundle\Controller\ExtJsController
    webit_sencha.touch_controller.class: Webit\Bundle\SenchaBundle\Controller\TouchController
    webit_sencha.store_controller.class: Webit\Bundle\SenchaBundle\Controller\StoreController
    webit_sencha.static_data_controller.class: Webit\Bundle\SenchaBundle\Controller\StaticDataController
    webit_sencha.tree_store_controller.class: Webit\Bundle\SenchaBundle\Controller\TreeStoreController
    webit_sencha.store_provider.class: Webit\Bundle\SenchaBundle\Component\Store\StoreProvider
    webit_sencha.store_request_filter_provider.class: Webit\Bundle\SenchaBundle\Component\Store\StoreRequestFilterProvider
    webit_sencha.store_request_factory.class: Webit\Bundle\SenchaBundle\Component\Store\StoreRequestFactory
    webit_sencha.store_response_configuration_provider.class: Webit\Bundle\SenchaBundle\Component\Store\Configuration\ResponseConfigurationProvider
    webit_sencha.store_controller_filter_listener.class: Webit\Bundle\SenchaBundle\Listener\StoreControllerFilter
    webit_sencha.store_request_filter_listener.class: Webit\Bundle\SenchaBundle\Listener\StoreRequestFilter
    webit_sencha.store_response_filter_listener.class: Webit\Bundle\SenchaBundle\Listener\StoreResponseFilter
    webit_sencha.pre_deserialize_listener.class: Webit\Tools\Data\PreDeserializeListener
    webit_sencha.static_data_exposer.class: Webit\Bundle\SenchaBundle\StaticData\StaticDataExposer
    webit_sencha.data_exposer.security.class: Webit\Bundle\SenchaBundle\StaticData\SecurityDataExposer
    webit_sencha.collection_serializer_handler.class: Webit\Tools\Data\CollectionSerializationHandler
    
services:
    webit_sencha.installer:
        class: %webit_sencha.installer.class%
        arguments: [%webit_sencha.assets_dir%, { extjs: %webit_sencha.extjs_url_list%, touch: %webit_sencha.touch_url_list% }]
    webit_sencha.extjs_controller:
        class: %webit_sencha.extjs_controller.class%
        arguments: [@service_container]
    webit_sencha.static_data_controller:
        class: %webit_sencha.static_data_controller.class%
        calls:
            - [setContainer, [@service_container]]
    webit_sencha.touch_controller:
        class: %webit_sencha.touch_controller.class%
        arguments: [@service_container]
    webit_sencha.store_controller:
        class: %webit_sencha.store_controller.class%
        calls:
            - [setContainer,[@service_container]]
    webit_sencha.tree_store_controller:
        class: %webit_sencha.tree_store_controller.class%
        calls:
            - [setContainer,[@service_container]]
    webit_sencha.store_provider:
        class: %webit_sencha.store_provider.class%
    webit_sencha.store_request_filter_provider:
        class: %webit_sencha.store_request_filter_provider.class%
    webit_sencha.store_request_factory:
        class: %webit_sencha.store_request_factory.class%
        arguments: [{},@request, @serializer]
        scope: request
    webit_sencha.store_response_configuration_provider:
        class: %webit_sencha.store_response_configuration_provider.class%
    webit_sencha.store_controller_filter_listener:
        class: %webit_sencha.store_controller_filter_listener.class%
        arguments: [@webit_sencha.store_provider, @webit_sencha.store_request_factory, %webit_sencha.request_store_key%]
        scope: request
        tags:
            - { name: kernel.event_subscriber }
    webit_sencha.store_request_filter_listener:
        class: %webit_sencha.store_request_filter_listener.class%
        arguments: [@webit_sencha.store_request_filter_provider]
        scope: request
        tags:
            - { name: kernel.event_subscriber }
    webit_sencha.store_response_filter_listener:
        class: %webit_sencha.store_response_filter_listener.class%
        arguments: [@webit_sencha.store_response_configuration_provider]
        tags:
            - { name: kernel.event_subscriber }
    webit_sencha.static_data_exposer:
        class: %webit_sencha.static_data_exposer.class%
    webit_sencha.data_exposer.security:
        class: %webit_sencha.data_exposer.security.class%
        arguments: [@security.context, %webit_sencha.security.user_model%]
        tags:
           - { name: webit_sencha.static_data_exposer }
    webit_sencha.collection_serializer_handler:
        class: %webit_sencha.collection_serializer_handler.class%
        tags:
          - { name: jms_serializer.subscribing_handler }